const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.Rotate,
		C3.Behaviors.Flash,
		C3.Behaviors.Fade,
		C3.Behaviors.Timer,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Behaviors.Tween,
		C3.Plugins.Keyboard,
		C3.Behaviors.Bullet,
		C3.Behaviors.scrollto,
		C3.Plugins.TiledBg,
		C3.Plugins.Audio,
		C3.Behaviors.Sin,
		C3.Behaviors.NoSave,
		C3.Behaviors.destroy,
		C3.Behaviors.Pin,
		C3.Plugins.Spritefont2,
		C3.Plugins.Particles,
		C3.Plugins.Touch,
		C3.Behaviors.jumpthru,
		C3.Behaviors.LOS,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.MoveTo,
		C3.Plugins.LocalStorage,
		C3.Plugins.Arr,
		C3.Plugins.Browser,
		C3.Plugins.gamepad,
		C3.Plugins.Mouse,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.mid,
		C3.Plugins.System.Exps.layoutname,
		C3.ScriptsInEvents["E-Game_Event2_Act2"],
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.gamepad.Cnds.IsButtonDown,
		C3.Plugins.gamepad.Cnds.CompareAxis,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.gamepad.Cnds.OnButtonDown,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Behaviors.Platform.Acts.SetGravity,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Platform.Acts.SetMaxFallSpeed,
		C3.Behaviors.Rotate.Cnds.IsEnabled,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Platform.Exps.VectorY,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Spritefont2.Acts.MoveToLayer,
		C3.Plugins.Spritefont2.Acts.MoveToBottom,
		C3.ScriptsInEvents["E-Game_Event160_Act2"],
		C3.ScriptsInEvents["E-Game_Event160_Act4"],
		C3.ScriptsInEvents["E-Game_Event160_Act6"],
		C3.ScriptsInEvents["E-Game_Event161_Act3"],
		C3.ScriptsInEvents["E-Game_Event162_Act4"],
		C3.ScriptsInEvents["E-Game_Event163_Act3"],
		C3.ScriptsInEvents["E-Game_Event164_Act3"],
		C3.ScriptsInEvents["E-Game_Event165_Act3"],
		C3.ScriptsInEvents["E-Game_Event166_Act3"],
		C3.ScriptsInEvents["E-Game_Event167_Act3"],
		C3.ScriptsInEvents["E-Game_Event168_Act4"],
		C3.ScriptsInEvents["E-Game_Event169_Act3"],
		C3.ScriptsInEvents["E-Game_Event170_Act4"],
		C3.ScriptsInEvents["E-Game_Event171_Act3"],
		C3.ScriptsInEvents["E-Game_Event172_Act3"],
		C3.ScriptsInEvents["E-Game_Event173_Act3"],
		C3.ScriptsInEvents["E-Game_Event174_Act3"],
		C3.ScriptsInEvents["E-Game_Event175_Act3"],
		C3.ScriptsInEvents["E-Game_Event176_Act3"],
		C3.ScriptsInEvents["E-Game_Event177_Act3"],
		C3.ScriptsInEvents["E-Game_Event178_Act3"],
		C3.ScriptsInEvents["E-Game_Event179_Act3"],
		C3.ScriptsInEvents["E-Game_Event180_Act4"],
		C3.ScriptsInEvents["E-Game_Event181_Act3"],
		C3.ScriptsInEvents["E-Game_Event182_Act3"],
		C3.ScriptsInEvents["E-Game_Event183_Act3"],
		C3.ScriptsInEvents["E-Game_Event184_Act3"],
		C3.ScriptsInEvents["E-Game_Event185_Act3"],
		C3.ScriptsInEvents["E-Game_Event186_Act3"],
		C3.ScriptsInEvents["E-Game_Event187_Act3"],
		C3.ScriptsInEvents["E-Game_Event188_Act3"],
		C3.ScriptsInEvents["E-Game_Event189_Act3"],
		C3.ScriptsInEvents["E-Game_Event190_Act3"],
		C3.ScriptsInEvents["E-Game_Event191_Act3"],
		C3.ScriptsInEvents["E-Game_Event192_Act5"],
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Spritefont2.Cnds.IsOnScreen,
		C3.Plugins.Spritefont2.Cnds.IsVisible,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Plugins.Particles.Acts.SetVisible,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Particles.Acts.SetPos,
		C3.Plugins.System.Cnds.IsMobile,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Behaviors.jumpthru.Acts.SetEnabled,
		C3.Plugins.TiledBg.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.TiledBg.Cnds.OnDestroyed,
		C3.Plugins.TiledBg.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Behaviors.Flash.Cnds.IsFlashing,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Behaviors.Bullet.Cnds.IsEnabled,
		C3.Plugins.Audio.Acts.Stop,
		C3.Behaviors.Bullet.Acts.SetGravity,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Timer.Acts.PauseResumeTimer,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Behaviors.Platform.Acts.SetJumpStrength,
		C3.Behaviors.Flash.Acts.StopFlashing,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Behaviors.Timer.Acts.StopAllTimers,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.ScriptsInEvents["E-Enemies_Event260_Act1"],
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.Audio.Acts.StopAll,
		C3.ScriptsInEvents["E-Enemies_Event263_Act1"],
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.ScriptsInEvents["E-Enemies_Event268_Act15"],
		C3.Behaviors.Bullet.Cnds.CompareSpeed,
		C3.Plugins.Spritefont2.Acts.SetAngle,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Spritefont2.Acts.RotateCounterclockwise,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Behaviors.Platform.Cnds.IsByWall,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Behaviors.LOS.Acts.CastRay,
		C3.Behaviors.LOS.Cnds.RayIntersected,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Behaviors.LOS.Exps.HitX,
		C3.Behaviors.LOS.Exps.HitY,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Behaviors.Platform.Acts.SetAcceleration,
		C3.Behaviors.Platform.Acts.SetDeceleration,
		C3.Behaviors.Fade.Cnds.OnFadeInEnd,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.System.Acts.GoToLayout,
		C3.ScriptsInEvents["E-Level01_Event10_Act4"],
		C3.ScriptsInEvents["E-Level01_Event11_Act4"],
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.ScriptsInEvents["E-Level03_Event4_Act4"],
		C3.ScriptsInEvents["E-Level03_Event5_Act4"],
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.ScriptsInEvents["E-Level02_Event4_Act4"],
		C3.ScriptsInEvents["E-Level02_Event5_Act4"],
		C3.ScriptsInEvents["E-Level04_Event4_Act4"],
		C3.ScriptsInEvents["E-Level04_Event5_Act4"],
		C3.ScriptsInEvents["E-Level05_Event4_Act4"],
		C3.ScriptsInEvents["E-Level05_Event5_Act4"],
		C3.ScriptsInEvents["E-Level06_Event5_Act4"],
		C3.ScriptsInEvents["E-Level06_Event6_Act4"],
		C3.ScriptsInEvents["E-Level07_Event5_Act4"],
		C3.ScriptsInEvents["E-Level07_Event6_Act4"],
		C3.ScriptsInEvents["E-Level08_Event5_Act4"],
		C3.ScriptsInEvents["E-Level08_Event6_Act4"],
		C3.ScriptsInEvents["E-Level09_Event7_Act4"],
		C3.ScriptsInEvents["E-Level09_Event8_Act4"],
		C3.ScriptsInEvents["E-Level10_Event5_Act4"],
		C3.ScriptsInEvents["E-Level10_Event6_Act4"],
		C3.ScriptsInEvents["E-Level11_Event5_Act4"],
		C3.ScriptsInEvents["E-Level11_Event6_Act4"],
		C3.ScriptsInEvents["E-Level13_Event5_Act4"],
		C3.ScriptsInEvents["E-Level13_Event6_Act4"],
		C3.ScriptsInEvents["E-Level14_Event5_Act4"],
		C3.ScriptsInEvents["E-Level14_Event6_Act4"],
		C3.ScriptsInEvents["E-Level15_Event5_Act4"],
		C3.ScriptsInEvents["E-Level15_Event6_Act4"],
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.ScriptsInEvents["E-Menu_Event23_Act2"],
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.ScriptsInEvents["E-Intro_Event4_Act6"],
		C3.Plugins.Audio.Acts.SetVolume,
		C3.ScriptsInEvents["E-Intro02_Event5_Act4"],
		C3.ScriptsInEvents["E-Intro02_Event12_Act6"],
		C3.Plugins.Spritefont2.Acts.SetEffectParam,
		C3.Plugins.Spritefont2.Cnds.CompareText,
		C3.ScriptsInEvents["E-Options_Event43_Act1"],
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Spritefont2.Acts.SetOpacity,
		C3.Plugins.Spritefont2.Cnds.CompareOpacity,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.ScriptsInEvents["E-Level12_Event5_Act4"],
		C3.ScriptsInEvents["E-Level12_Event6_Act4"],
		C3.ScriptsInEvents["E-Boss_Event4_Act4"],
		C3.ScriptsInEvents["E-Boss_Event5_Act4"],
		C3.ScriptsInEvents["E-Boss_Event8_Act5"],
		C3.ScriptsInEvents["E-Boss_Event8_Act7"],
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.ScriptsInEvents["E-Boss_Event9_Act4"],
		C3.ScriptsInEvents["E-Boss_Event10_Act5"],
		C3.ScriptsInEvents["E-Boss_Event34_Act2"],
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.ScriptsInEvents["E-Ui_Event7_Act1"],
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.System.Acts.SetTimescale,
		C3.ScriptsInEvents["E-Ui_Event8_Act1"],
		C3.Plugins.System.Acts.RestartLayout,
		C3.ScriptsInEvents["E-Ui_Event26_Act8"],
		C3.ScriptsInEvents["E-Ui_Event26_Act9"],
		C3.Plugins.Sprite.Cnds.IsCollisionEnabled,
		C3.Plugins.Arr.Acts.SetX,
		C3.ScriptsInEvents["E-Ui_Event49_Act8"],
		C3.ScriptsInEvents["E-Ui_Event49_Act9"],
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.ScriptsInEvents["E-Ui_Event50_Act37"],
		C3.ScriptsInEvents["E-Ui_Event50_Act38"],
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.ScriptsInEvents.Loadingsavedata_Event6_Act1,
		C3.Plugins.Browser.Exps.ExecJS,
		C3.ScriptsInEvents.Loadingsavedata_Event7_Act1,
		C3.ScriptsInEvents.Loadingsavedata_Event8_Act1,
		C3.ScriptsInEvents.Loadingsavedata_Event8_Act2,
		C3.ScriptsInEvents.Loadingsavedata_Event8_Act3,
		C3.ScriptsInEvents.Loadingsavedata_Event8_Act4,
		C3.ScriptsInEvents.Loadingsavedata_Event8_Act5,
		C3.ScriptsInEvents.Loadingsavedata_Event8_Act6,
		C3.ScriptsInEvents.Loadingsavedata_Event8_Act7,
		C3.ScriptsInEvents.Loadingsavedata_Event8_Act8,
		C3.ScriptsInEvents.Loadingsavedata_Event8_Act9,
		C3.ScriptsInEvents.Loadingsavedata_Event8_Act10,
		C3.ScriptsInEvents.Loadingsavedata_Event8_Act11,
		C3.ScriptsInEvents.Loadingsavedata_Event8_Act12,
		C3.ScriptsInEvents.Loadingsavedata_Event8_Act13,
		C3.ScriptsInEvents.Loadingsavedata_Event8_Act14,
		C3.ScriptsInEvents.Loadingsavedata_Event8_Act15,
		C3.ScriptsInEvents.Loadingsavedata_Event8_Act16,
		C3.ScriptsInEvents.Loadingsavedata_Event8_Act17,
		C3.ScriptsInEvents.Loadingsavedata_Event8_Act18,
		C3.ScriptsInEvents.Loadingsavedata_Event8_Act19,
		C3.ScriptsInEvents.Loadingsavedata_Event8_Act20,
		C3.ScriptsInEvents.Loadingsavedata_Event8_Act21,
		C3.ScriptsInEvents.Loadingsavedata_Event8_Act22,
		C3.ScriptsInEvents.Loadingsavedata_Event8_Act23,
		C3.ScriptsInEvents.Loadingsavedata_Event8_Act24,
		C3.ScriptsInEvents.Loadingsavedata_Event8_Act25,
		C3.ScriptsInEvents.Loadingsavedata_Event8_Act26,
		C3.ScriptsInEvents.Loadingsavedata_Event8_Act27,
		C3.ScriptsInEvents.Loadingsavedata_Event8_Act28,
		C3.ScriptsInEvents.Loadingsavedata_Event8_Act29,
		C3.ScriptsInEvents.Loadingsavedata_Event8_Act30,
		C3.ScriptsInEvents.Loadingsavedata_Event8_Act31,
		C3.ScriptsInEvents.Loadingsavedata_Event8_Act32,
		C3.ScriptsInEvents.Loadingsavedata_Event8_Act33,
		C3.ScriptsInEvents.Loadingsavedata_Event8_Act34,
		C3.ScriptsInEvents.Loadingsavedata_Event8_Act35,
		C3.ScriptsInEvents.Loadingsavedata_Event8_Act36,
		C3.ScriptsInEvents.Loadingsavedata_Event8_Act37,
		C3.Behaviors.Fade.Cnds.OnWaitEnd,
		C3.ScriptsInEvents["E-Final03_Event10_Act4"],
		C3.ScriptsInEvents["E-Final03_Event11_Act4"],
		C3.ScriptsInEvents["E-Ads_Event1_Act4"],
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.ScriptsInEvents["E-Ads_Event2_Act4"],
		C3.ScriptsInEvents["E-Loading_crazy_Event1_Act2"]
	];
};
self.C3_JsPropNameTable = [
	{jet: 0},
	{Platform: 0},
	{Rotate: 0},
	{Flash: 0},
	{Fade: 0},
	{Fade2: 0},
	{Timer: 0},
	{player: 0},
	{Tilemap: 0},
	{Solid: 0},
	{Colision: 0},
	{Tween: 0},
	{alma_player: 0},
	{Keyboard: 0},
	{direction: 0},
	{zombie: 0},
	{block_mask: 0},
	{Bullet: 0},
	{particle_block: 0},
	{item: 0},
	{coin_timer: 0},
	{block: 0},
	{position: 0},
	{ScrollTo: 0},
	{camera: 0},
	{rigth_r: 0},
	{left_e: 0},
	{Audio: 0},
	{bg11: 0},
	{bg10: 0},
	{bg13: 0},
	{bg15: 0},
	{coin: 0},
	{star: 0},
	{moeda: 0},
	{Sine: 0},
	{NoSave: 0},
	{Water: 0},
	{water_botton: 0},
	{jump: 0},
	{DestroyOutsideLayout: 0},
	{fish: 0},
	{water_overlap: 0},
	{trampolim: 0},
	{orange: 0},
	{colision_enemies2: 0},
	{colision_enemies: 0},
	{octopus: 0},
	{orange_fly: 0},
	{orange_sine: 0},
	{life: 0},
	{ball: 0},
	{level: 0},
	{portal: 0},
	{star_mask: 0},
	{Pin: 0},
	{life_item: 0},
	{life_item3: 0},
	{star_mask2: 0},
	{gui_heart: 0},
	{heart_text: 0},
	{scorenumber_text: 0},
	{painel_powerup: 0},
	{gui_life: 0},
	{score_text: 0},
	{score: 0},
	{score_enemies: 0},
	{Text_heart: 0},
	{ring_text: 0},
	{gui_coin: 0},
	{paused: 0},
	{btn_pause: 0},
	{water_splash: 0},
	{bubble: 0},
	{portal2: 0},
	{bullet_player: 0},
	{gui_powerup: 0},
	{star_power: 0},
	{power_item: 0},
	{power: 0},
	{star_crystal: 0},
	{Touch: 0},
	{control_left: 0},
	{control_rigth: 0},
	{control_jump: 0},
	{control_fire: 0},
	{alavanca: 0},
	{traps: 0},
	{time: 0},
	{button: 0},
	{particle_block2: 0},
	{spike: 0},
	{block_enter: 0},
	{angle_snake: 0},
	{snake: 0},
	{orange_bullet: 0},
	{Jumpthru: 0},
	{jumpthru: 0},
	{portal_bonus01: 0},
	{jet_player: 0},
	{plataform_sine: 0},
	{X_Position: 0},
	{Y_Position: 0},
	{Fall: 0},
	{plataform_fall: 0},
	{mode: 0},
	{box: 0},
	{bg16: 0},
	{portal_bonus2: 0},
	{box_fall: 0},
	{canhao: 0},
	{bullet_canhao: 0},
	{obj_sinefloat: 0},
	{TiledBackground: 0},
	{TiledBackground2: 0},
	{TiledBackground3: 0},
	{Tilemap2: 0},
	{die: 0},
	{rotate: 0},
	{crab: 0},
	{overlap_enemies: 0},
	{Water02: 0},
	{Water3: 0},
	{TiledBackground4: 0},
	{bee: 0},
	{particle_cristal: 0},
	{caramujo: 0},
	{canhao2: 0},
	{bullet_canhao2: 0},
	{nuvem: 0},
	{nuvem2: 0},
	{Tilemap3: 0},
	{background: 0},
	{bastao: 0},
	{base_rotate: 0},
	{corrente: 0},
	{saw: 0},
	{obj_fire: 0},
	{obj_bee: 0},
	{mush_spike: 0},
	{obj_rock_opacity: 0},
	{obj_acid: 0},
	{robo_big: 0},
	{robo: 0},
	{fire: 0},
	{fire2: 0},
	{orange_spike: 0},
	{fire3: 0},
	{LineOfSight: 0},
	{orc: 0},
	{playerDetected: 0},
	{Pathfinding: 0},
	{MoveTo: 0},
	{Sine2: 0},
	{bat: 0},
	{explosion: 0},
	{fire4: 0},
	{ball_spike: 0},
	{var_life: 0},
	{obj_turtle: 0},
	{bullet_spike: 0},
	{força: 0 },
	{projetil2: 0},
	{stop: 0},
	{esquilo: 0},
	{spider: 0},
	{teia: 0},
	{rain: 0},
	{barril: 0},
	{move: 0},
	{plataform: 0},
	{triangle: 0},
	{eletrical: 0},
	{ball_spike2: 0},
	{ball_spike3: 0},
	{ball_spike4: 0},
	{nuvem3: 0},
	{nuvem4: 0},
	{fall: 0},
	{spike_fall: 0},
	{ball_fly: 0},
	{TiledBackground5: 0},
	{nuvem5: 0},
	{fish_horizontal: 0},
	{Rotate2: 0},
	{crab2: 0},
	{speed: 0},
	{fish_direction: 0},
	{frog: 0},
	{frog2: 0},
	{frog3: 0},
	{frog4: 0},
	{mush_spike2: 0},
	{overlap_winter: 0},
	{kiwi_ice: 0},
	{TiledBackground6: 0},
	{block_ice: 0},
	{ball_flySine: 0},
	{explosion2: 0},
	{base_laserV: 0},
	{laserV: 0},
	{base_laserH: 0},
	{laserH: 0},
	{faisca: 0},
	{faisca2: 0},
	{faisca3: 0},
	{knight: 0},
	{robo_blue: 0},
	{dust: 0},
	{ship: 0},
	{TiledBackground9: 0},
	{lua: 0},
	{TiledBackground10: 0},
	{ship_fire: 0},
	{bullet_ship: 0},
	{base_laserV2: 0},
	{laserV2: 0},
	{dust_enemies: 0},
	{ship_sine: 0},
	{ceilingTrap: 0},
	{ceilingTrap2: 0},
	{ship_fire2: 0},
	{ship_fire3: 0},
	{faisca_state: 0},
	{flash: 0},
	{faisca4: 0},
	{Firework: 0},
	{Tv: 0},
	{house: 0},
	{mush_spike3: 0},
	{mush_spike4: 0},
	{score_star: 0},
	{btn_play: 0},
	{btn_options: 0},
	{btn_credits: 0},
	{btn_flash: 0},
	{baby_font: 0},
	{chicco_font: 0},
	{adventure_font: 0},
	{logo: 0},
	{btn_music: 0},
	{value: 0},
	{text_music: 0},
	{btn_controls: 0},
	{btn_deleteSave: 0},
	{Tilemap4: 0},
	{bg17: 0},
	{flash_white: 0},
	{ToolTip: 0},
	{rains: 0},
	{Fade3: 0},
	{Fade4: 0},
	{player2: 0},
	{fio: 0},
	{orange2: 0},
	{tetris: 0},
	{chuva: 0},
	{particle_chuva: 0},
	{expression: 0},
	{arcade: 0},
	{portal_explode: 0},
	{btn_back: 0},
	{LocalStorage: 0},
	{keys: 0},
	{text_T: 0},
	{levelnumber: 0},
	{moldura: 0},
	{SF_Nr: 0},
	{star_levelselect01: 0},
	{star_levelselect2: 0},
	{star_levelselect3: 0},
	{star_levelselect4: 0},
	{star_levelselect5: 0},
	{star_levelselect6: 0},
	{star_levelselect7: 0},
	{star_levelselect8: 0},
	{star_levelselect9: 0},
	{star_levelselect10: 0},
	{star_levelselect11: 0},
	{star_levelselect12: 0},
	{star_levelselect13: 0},
	{star_levelselect14: 0},
	{star_levelselect15: 0},
	{levelSelect: 0},
	{btn_flash2: 0},
	{Array: 0},
	{painel: 0},
	{btn_nextlevel: 0},
	{btn_menuUI2: 0},
	{btn_AD: 0},
	{maxscore_painel: 0},
	{scorenumber_painel: 0},
	{scores: 0},
	{star_painel: 0},
	{shadow: 0},
	{painel_paused: 0},
	{btn_restartUI: 0},
	{btn_menuUI: 0},
	{paused_text: 0},
	{new_maxscore: 0},
	{levelCompleted: 0},
	{painel_UI: 0},
	{watch_ad2: 0},
	{levelCompleted2: 0},
	{revive: 0},
	{text_gameOver01: 0},
	{text_gameOver03: 0},
	{lost_life: 0},
	{painel_move: 0},
	{game_over: 0},
	{gui_star: 0},
	{Browser: 0},
	{bg18: 0},
	{SF_Text: 0},
	{font_credits: 0},
	{keys_tutorial: 0},
	{text_tutorial: 0},
	{text_tutorial02: 0},
	{text_title: 0},
	{text_title2: 0},
	{painel2: 0},
	{Tv2: 0},
	{bullet_player2: 0},
	{BOSS: 0},
	{bullet_boss01: 0},
	{bullet_boss02: 0},
	{penguin: 0},
	{text_music2: 0},
	{pingo: 0},
	{destroy_bullet: 0},
	{logo_crazygames: 0},
	{Gamepad: 0},
	{Type: 0},
	{Revive_Player: 0},
	{ad: 0},
	{watch_ads: 0},
	{btn_Skip: 0},
	{Mouse: 0},
	{IsTouch: 0},
	{Language: 0},
	{SF_GameTExt: 0},
	{Torch: 0},
	{spr_watch_ads: 0},
	{Active: 0},
	{Booster: 0},
	{power_booster: 0},
	{controles: 0},
	{coins: 0},
	{water: 0},
	{heart: 0},
	{play: 0},
	{bullet: 0},
	{audio: 0},
	{levelCleared: 0},
	{currentLevel: 0},
	{pause: 0},
	{total_score: 0},
	{max_score: 0},
	{Revive: 0},
	{X_revive: 0},
	{Y_revive: 0},
	{Star_power_destroyed: 0},
	{Star_power_destroyed2: 0},
	{star01: 0},
	{intro: 0},
	{score_01: 0},
	{music: 0},
	{star03: 0},
	{score_03: 0},
	{star02: 0},
	{score_02: 0},
	{star04: 0},
	{score_04: 0},
	{star05: 0},
	{score_05: 0},
	{star06: 0},
	{score_06: 0},
	{star07: 0},
	{score_07: 0},
	{star08: 0},
	{score_08: 0},
	{star09: 0},
	{score_09: 0},
	{star10: 0},
	{score_10: 0},
	{star11: 0},
	{score_11: 0},
	{star13: 0},
	{score_13: 0},
	{star14: 0},
	{score_14: 0},
	{star15: 0},
	{score_15: 0},
	{btn: 0},
	{Skip_menu: 0},
	{btn2: 0},
	{star12: 0},
	{score_12: 0},
	{finish: 0},
	{PAUSEGAME: 0},
	{SDKReady: 0}
];

self.InstanceType = {
	player: class extends self.ISpriteInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	Colision: class extends self.ISpriteInstance {},
	alma_player: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	zombie: class extends self.ISpriteInstance {},
	block_mask: class extends self.ISpriteInstance {},
	particle_block: class extends self.ISpriteInstance {},
	block: class extends self.ISpriteInstance {},
	camera: class extends self.ISpriteInstance {},
	rigth_r: class extends self.ITiledBackgroundInstance {},
	left_e: class extends self.ITiledBackgroundInstance {},
	Audio: class extends self.IInstance {},
	coin_timer: class extends self.ISpriteInstance {},
	bg11: class extends self.ITiledBackgroundInstance {},
	bg10: class extends self.ITiledBackgroundInstance {},
	bg13: class extends self.ITiledBackgroundInstance {},
	bg15: class extends self.ITiledBackgroundInstance {},
	coin: class extends self.ISpriteInstance {},
	star: class extends self.ISpriteInstance {},
	moeda: class extends self.ITiledBackgroundInstance {},
	Water: class extends self.ISpriteInstance {},
	water_botton: class extends self.ISpriteInstance {},
	fish: class extends self.ISpriteInstance {},
	water_overlap: class extends self.ITiledBackgroundInstance {},
	trampolim: class extends self.ISpriteInstance {},
	orange: class extends self.ISpriteInstance {},
	colision_enemies2: class extends self.ISpriteInstance {},
	colision_enemies: class extends self.ISpriteInstance {},
	octopus: class extends self.ISpriteInstance {},
	orange_fly: class extends self.ISpriteInstance {},
	orange_sine: class extends self.ISpriteInstance {},
	ball: class extends self.ISpriteInstance {},
	portal: class extends self.ISpriteInstance {},
	star_mask: class extends self.ISpriteInstance {},
	life_item: class extends self.ISpriteInstance {},
	life_item3: class extends self.ISpriteInstance {},
	star_mask2: class extends self.ISpriteInstance {},
	gui_heart: class extends self.ISpriteInstance {},
	heart_text: class extends self.ISpriteFontInstance {},
	scorenumber_text: class extends self.ISpriteFontInstance {},
	painel_powerup: class extends self.ISpriteInstance {},
	gui_life: class extends self.ISpriteInstance {},
	score_text: class extends self.ISpriteFontInstance {},
	score_enemies: class extends self.ISpriteFontInstance {},
	Text_heart: class extends self.ISpriteFontInstance {},
	ring_text: class extends self.ISpriteFontInstance {},
	gui_coin: class extends self.ISpriteInstance {},
	btn_pause: class extends self.ISpriteInstance {},
	water_splash: class extends self.ISpriteInstance {},
	bubble: class extends self.ISpriteInstance {},
	portal2: class extends self.ISpriteInstance {},
	bullet_player: class extends self.ISpriteInstance {},
	gui_powerup: class extends self.ISpriteInstance {},
	star_power: class extends self.ISpriteInstance {},
	power_item: class extends self.ISpriteInstance {},
	power: class extends self.IParticlesInstance {},
	star_crystal: class extends self.ISpriteInstance {},
	jet: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	control_left: class extends self.ISpriteInstance {},
	control_rigth: class extends self.ISpriteInstance {},
	control_jump: class extends self.ISpriteInstance {},
	control_fire: class extends self.ISpriteInstance {},
	button: class extends self.ISpriteInstance {},
	particle_block2: class extends self.ISpriteInstance {},
	spike: class extends self.ISpriteInstance {},
	block_enter: class extends self.ISpriteInstance {},
	snake: class extends self.ISpriteInstance {},
	orange_bullet: class extends self.ISpriteInstance {},
	jumpthru: class extends self.ISpriteInstance {},
	portal_bonus01: class extends self.ISpriteInstance {},
	jet_player: class extends self.ISpriteInstance {},
	plataform_sine: class extends self.ISpriteInstance {},
	plataform_fall: class extends self.ISpriteInstance {},
	box: class extends self.ISpriteInstance {},
	bg16: class extends self.ITiledBackgroundInstance {},
	portal_bonus2: class extends self.ISpriteInstance {},
	box_fall: class extends self.ISpriteInstance {},
	canhao: class extends self.ISpriteInstance {},
	bullet_canhao: class extends self.ISpriteInstance {},
	obj_sinefloat: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	Tilemap2: class extends self.ITilemapInstance {},
	crab: class extends self.ISpriteInstance {},
	overlap_enemies: class extends self.ITiledBackgroundInstance {},
	Water02: class extends self.ISpriteInstance {},
	Water3: class extends self.ISpriteInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	bee: class extends self.ISpriteInstance {},
	particle_cristal: class extends self.IParticlesInstance {},
	caramujo: class extends self.ISpriteInstance {},
	canhao2: class extends self.ISpriteInstance {},
	bullet_canhao2: class extends self.ISpriteInstance {},
	nuvem: class extends self.ITiledBackgroundInstance {},
	nuvem2: class extends self.ITiledBackgroundInstance {},
	Tilemap3: class extends self.ITilemapInstance {},
	background: class extends self.ITilemapInstance {},
	bastao: class extends self.ISpriteInstance {},
	base_rotate: class extends self.ISpriteInstance {},
	corrente: class extends self.ISpriteInstance {},
	saw: class extends self.ISpriteInstance {},
	obj_fire: class extends self.ISpriteInstance {},
	obj_bee: class extends self.ISpriteInstance {},
	mush_spike: class extends self.ISpriteInstance {},
	obj_rock_opacity: class extends self.ISpriteInstance {},
	obj_acid: class extends self.ISpriteInstance {},
	robo_big: class extends self.ISpriteInstance {},
	robo: class extends self.ISpriteInstance {},
	fire: class extends self.ISpriteInstance {},
	fire2: class extends self.ISpriteInstance {},
	orange_spike: class extends self.ISpriteInstance {},
	fire3: class extends self.ISpriteInstance {},
	orc: class extends self.ISpriteInstance {},
	bat: class extends self.ISpriteInstance {},
	explosion: class extends self.ISpriteInstance {},
	fire4: class extends self.ISpriteInstance {},
	ball_spike: class extends self.ISpriteInstance {},
	obj_turtle: class extends self.ISpriteInstance {},
	bullet_spike: class extends self.ISpriteInstance {},
	projetil2: class extends self.ISpriteInstance {},
	esquilo: class extends self.ISpriteInstance {},
	spider: class extends self.ISpriteInstance {},
	teia: class extends self.ISpriteInstance {},
	rain: class extends self.ISpriteInstance {},
	barril: class extends self.ISpriteInstance {},
	plataform: class extends self.ISpriteInstance {},
	triangle: class extends self.ISpriteInstance {},
	eletrical: class extends self.ISpriteInstance {},
	ball_spike2: class extends self.ISpriteInstance {},
	ball_spike3: class extends self.ISpriteInstance {},
	ball_spike4: class extends self.ISpriteInstance {},
	nuvem3: class extends self.ITiledBackgroundInstance {},
	nuvem4: class extends self.ITiledBackgroundInstance {},
	spike_fall: class extends self.ISpriteInstance {},
	ball_fly: class extends self.ISpriteInstance {},
	TiledBackground5: class extends self.ITiledBackgroundInstance {},
	nuvem5: class extends self.ITiledBackgroundInstance {},
	fish_horizontal: class extends self.ISpriteInstance {},
	crab2: class extends self.ISpriteInstance {},
	fish_direction: class extends self.ISpriteInstance {},
	frog: class extends self.ISpriteInstance {},
	frog2: class extends self.ISpriteInstance {},
	frog3: class extends self.ISpriteInstance {},
	frog4: class extends self.ISpriteInstance {},
	mush_spike2: class extends self.ISpriteInstance {},
	overlap_winter: class extends self.ITiledBackgroundInstance {},
	kiwi_ice: class extends self.ISpriteInstance {},
	TiledBackground6: class extends self.ITiledBackgroundInstance {},
	block_ice: class extends self.ISpriteInstance {},
	ball_flySine: class extends self.ISpriteInstance {},
	explosion2: class extends self.ISpriteInstance {},
	base_laserV: class extends self.ISpriteInstance {},
	laserV: class extends self.ISpriteInstance {},
	base_laserH: class extends self.ISpriteInstance {},
	laserH: class extends self.ISpriteInstance {},
	faisca: class extends self.IParticlesInstance {},
	faisca2: class extends self.IParticlesInstance {},
	faisca3: class extends self.IParticlesInstance {},
	knight: class extends self.ISpriteInstance {},
	robo_blue: class extends self.ISpriteInstance {},
	dust: class extends self.ISpriteInstance {},
	ship: class extends self.ISpriteInstance {},
	TiledBackground9: class extends self.ITiledBackgroundInstance {},
	lua: class extends self.ITiledBackgroundInstance {},
	TiledBackground10: class extends self.ITiledBackgroundInstance {},
	ship_fire: class extends self.ISpriteInstance {},
	bullet_ship: class extends self.ISpriteInstance {},
	base_laserV2: class extends self.ISpriteInstance {},
	laserV2: class extends self.ISpriteInstance {},
	dust_enemies: class extends self.ISpriteInstance {},
	ship_sine: class extends self.ISpriteInstance {},
	ceilingTrap: class extends self.ISpriteInstance {},
	ceilingTrap2: class extends self.ISpriteInstance {},
	ship_fire2: class extends self.ISpriteInstance {},
	ship_fire3: class extends self.ISpriteInstance {},
	faisca_state: class extends self.IParticlesInstance {},
	flash: class extends self.ITiledBackgroundInstance {},
	faisca4: class extends self.IParticlesInstance {},
	Firework: class extends self.IParticlesInstance {},
	Tv: class extends self.ISpriteInstance {},
	house: class extends self.ISpriteInstance {},
	mush_spike3: class extends self.ISpriteInstance {},
	mush_spike4: class extends self.ISpriteInstance {},
	score_star: class extends self.ISpriteFontInstance {},
	btn_play: class extends self.ISpriteInstance {},
	btn_options: class extends self.ISpriteInstance {},
	btn_credits: class extends self.ISpriteInstance {},
	btn_flash: class extends self.ISpriteInstance {},
	baby_font: class extends self.ISpriteInstance {},
	chicco_font: class extends self.ISpriteInstance {},
	adventure_font: class extends self.ISpriteInstance {},
	logo: class extends self.ISpriteInstance {},
	btn_music: class extends self.ISpriteInstance {},
	text_music: class extends self.ISpriteFontInstance {},
	btn_controls: class extends self.ISpriteInstance {},
	btn_deleteSave: class extends self.ISpriteInstance {},
	Tilemap4: class extends self.ITilemapInstance {},
	bg17: class extends self.ITiledBackgroundInstance {},
	flash_white: class extends self.ITiledBackgroundInstance {},
	rains: class extends self.IParticlesInstance {},
	player2: class extends self.ISpriteInstance {},
	fio: class extends self.ISpriteInstance {},
	orange2: class extends self.ISpriteInstance {},
	tetris: class extends self.ISpriteInstance {},
	chuva: class extends self.ISpriteInstance {},
	particle_chuva: class extends self.IParticlesInstance {},
	expression: class extends self.ISpriteInstance {},
	arcade: class extends self.ISpriteInstance {},
	portal_explode: class extends self.ISpriteInstance {},
	btn_back: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	keys: class extends self.ISpriteInstance {},
	text_T: class extends self.ISpriteFontInstance {},
	moldura: class extends self.ISpriteInstance {},
	SF_Nr: class extends self.ISpriteFontInstance {},
	star_levelselect01: class extends self.ISpriteInstance {},
	star_levelselect2: class extends self.ISpriteInstance {},
	star_levelselect3: class extends self.ISpriteInstance {},
	star_levelselect4: class extends self.ISpriteInstance {},
	star_levelselect5: class extends self.ISpriteInstance {},
	star_levelselect6: class extends self.ISpriteInstance {},
	star_levelselect7: class extends self.ISpriteInstance {},
	star_levelselect8: class extends self.ISpriteInstance {},
	star_levelselect9: class extends self.ISpriteInstance {},
	star_levelselect10: class extends self.ISpriteInstance {},
	star_levelselect11: class extends self.ISpriteInstance {},
	star_levelselect12: class extends self.ISpriteInstance {},
	star_levelselect13: class extends self.ISpriteInstance {},
	star_levelselect14: class extends self.ISpriteInstance {},
	star_levelselect15: class extends self.ISpriteInstance {},
	levelSelect: class extends self.ISpriteInstance {},
	btn_flash2: class extends self.ISpriteInstance {},
	Array: class extends self.IArrayInstance {},
	painel: class extends self.ISpriteInstance {},
	btn_nextlevel: class extends self.ISpriteInstance {},
	btn_menuUI2: class extends self.ISpriteInstance {},
	btn_AD: class extends self.ISpriteInstance {},
	maxscore_painel: class extends self.ISpriteFontInstance {},
	scorenumber_painel: class extends self.ISpriteFontInstance {},
	scores: class extends self.ISpriteFontInstance {},
	star_painel: class extends self.ISpriteInstance {},
	shadow: class extends self.ISpriteInstance {},
	painel_paused: class extends self.ISpriteInstance {},
	btn_restartUI: class extends self.ISpriteInstance {},
	btn_menuUI: class extends self.ISpriteInstance {},
	paused_text: class extends self.ISpriteFontInstance {},
	new_maxscore: class extends self.ISpriteFontInstance {},
	levelCompleted: class extends self.ISpriteInstance {},
	painel_UI: class extends self.ITiledBackgroundInstance {},
	watch_ad2: class extends self.ISpriteFontInstance {},
	levelCompleted2: class extends self.ISpriteFontInstance {},
	revive: class extends self.ISpriteInstance {},
	text_gameOver01: class extends self.ISpriteFontInstance {},
	text_gameOver03: class extends self.ISpriteFontInstance {},
	lost_life: class extends self.ISpriteFontInstance {},
	painel_move: class extends self.ISpriteInstance {},
	game_over: class extends self.ISpriteFontInstance {},
	gui_star: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	bg18: class extends self.ITiledBackgroundInstance {},
	SF_Text: class extends self.ISpriteFontInstance {},
	font_credits: class extends self.ISpriteFontInstance {},
	keys_tutorial: class extends self.ISpriteInstance {},
	text_tutorial: class extends self.ISpriteFontInstance {},
	text_tutorial02: class extends self.ISpriteFontInstance {},
	text_title: class extends self.ISpriteFontInstance {},
	text_title2: class extends self.ISpriteFontInstance {},
	painel2: class extends self.ISpriteInstance {},
	Tv2: class extends self.ISpriteInstance {},
	bullet_player2: class extends self.ISpriteInstance {},
	BOSS: class extends self.ISpriteInstance {},
	bullet_boss01: class extends self.ISpriteInstance {},
	bullet_boss02: class extends self.ISpriteInstance {},
	penguin: class extends self.ISpriteInstance {},
	text_music2: class extends self.ISpriteFontInstance {},
	pingo: class extends self.ISpriteInstance {},
	destroy_bullet: class extends self.ISpriteInstance {},
	logo_crazygames: class extends self.ISpriteInstance {},
	Gamepad: class extends self.IInstance {},
	Revive_Player: class extends self.ISpriteInstance {},
	ad: class extends self.ISpriteInstance {},
	watch_ads: class extends self.ISpriteInstance {},
	btn_Skip: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	SF_GameTExt: class extends self.ISpriteFontInstance {},
	Torch: class extends self.ISpriteInstance {},
	spr_watch_ads: class extends self.ISpriteInstance {},
	Booster: class extends self.ITiledBackgroundInstance {},
	power_booster: class extends self.ISpriteInstance {},
	controles: class extends self.ISpriteInstance {}
}
